inPath=r'/home/cskin/cskin-firmware/cskin/input'
copyPath=r'/home/cskin/cskin-firmware/cskin/output'
outPath=r'/home/cskin/cskin-firmware/cskin/output'
colorPath=r'/home/cskin/cskin-firmware/cskin/color'
standardPath=r'/home/cskin/cskin-firmware/cskin/standard'
locationPath=r'/home/cskin/cskin-firmware/cskin/location'
testPath=r'/home/cskin/cskin-firmware/cskin/test'
